Repository BuildForSDGCohort2/whatz-hot-frontend, pull requests merged in 2020-09, with the labels that each got.

#20 [chore]: User auth layout
  package-lock.json
  package.json
  src/App.tsx
  src/container/Header.tsx
  src/container/UserauthHeader.tsx
  src/container/UserauthLogo.tsx
  src/images/signup_illustration.png
  src/index.tsx
  src/react-app-env.d.ts
Labels: chore, front-end

#22 Ft usersignuppage
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.tsx
  src/container/Homepage.tsx
  src/container/Spinnerui.tsx
  src/container/StyledFirebaseAuthUi.tsx
  src/container/UserauthHeader.tsx
  src/container/UserauthLogo.tsx
  src/container/VerifyEmail.tsx
  src/images/logo.jpg
  src/images/logo.png
  src/pages/user/Signup.tsx
  src/react-app-env.d.ts
  src/redux/actions/uiActions.ts
  src/redux/constants/constants.ts
  src/redux/index.ts
  src/redux/models/ui.ts
  src/redux/reducers/Ui.ts
  src/redux/types/actions.ts
  src/styles/Spinneruistyles.ts
  src/styles/VerifyemailStyle.ts
  src/styles/userauthstyles.ts
  src/utils/Auth.ts
  src/utils/Uiconfig.ts
Labels: feature, front-end

#25 [hotfix]: commit to force deployment
  src/container/Error404.tsx
Labels: bug, front-end

#26 [hotfix]: Netlify react router issue
  public/_redirects
  src/container/Header.tsx
Labels: bug, front-end
