Repository BuildForSDGCohort2/whatz-hot-frontend, pull requests merged in 2020-08, with the labels that each got.

#6 [chore]: Setup CI/CD with Github Actions and Codacy
  .github/workflows/staging.yml
  package.json
  src/App.css
  src/index.css
Labels: chore, front-end

#7 fix: add .eslintignore file
  .eslintignore
  .github/workflows/staging.yml
Labels: bug, front-end

#10 [bug-fix]: Persist Build Directory between Jobs in Github Actions
  .github/workflows/staging.yml
Labels: bug, front-end

#13 chore- initial setup
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.test.js
  src/App.tsx
  src/__tests__/integration/App.test.tsx
  src/container/Error404.tsx
  src/container/Header.tsx
  src/helpers/axios.ts
  src/helpers/constants.ts
  src/index.tsx
  src/react-app-env.d.ts
  tsconfig.json
  yarn.lock
Labels: chore
